// Architeuthis Dux (Giant Atlantic Squid)
// Dillon et al
// 2AFC verb / pronoun continuation task

// Do show progress bar (fine! I give in)
var showProgressBar = true;

// Main shuffleSequence definition
var shuffleSequence = seq(
    'consent',
    'intro',
    'shared-intro',
    sepWith("timeoutSep",rshuffle(startsWith('ARCHITEUTHIS'),startsWith('MENTALIS'),startsWith('filler'))),
    'debrief'
     );

// Using modified controller coded by Ethan Poole (Umass, 2017)
// Disallows use of mouse for responses.
var DS = 'EPDashedAcceptabilityJudgment';

//  Set the Prolific Academic Completion URL
var sendingResultsMessage = "Please wait. Your data are being sent to the server."; 
var completionMessage = "Thank you for your participation. Your completion code is ASRJCD6V. To complete this experiment, go to: https://app.prolific.ac/submissions/complete?cc=ASRJCD6V."; 
var completionErrorMessage = "There was an error in sending your data to the server. You may still complete this experiment. Your completion code is ASRJCD6V. Please go to: https://app.prolific.ac/submissions/complete?cc=ASRJCD6V."; 

// Controller settings.
// Parameter settings taken from Staub 2009
var defaults = [
    "EPDashedSentence", {
        mode: 'speeded acceptability',
        display: 'in place',
        blankText: '+',
        wordTime: 1000,
        wordPauseTime: 150
        },
        DS, {randomOrder: false,
        presentHorizontally: true,
        mode: 'speeded acceptability',
        display: 'in place',
        blankText: '+',
        wordTime: 250,
        wordPauseTime: 150,
        timeout: null,
        hasCorrect: 1,
        q: ''}
];

// Add breaks every 24 items
function modifyRunningOrder(ro)
{
    for (var i = 0; i < ro.length; ++i)
    {
        if (i % 24 == 1
            && i > 23
            && i < 250)
        {
            ro[i].push(new DynamicElement(
                "Message",
                {html: "<p>Please take a short break. Press a button to continue when you're ready.</p>", transfer: "keypress"},
            true));
            ro[i].push(new DynamicElement(
                "Separator",
                {transfer: 2500, normalMessage: "Hands in place! Your first sentence of this block will start soon."},
            true));
        }
    }
    return ro;
}

// Items array.
var items = [

["timeoutSep", Separator, { transfer: 250, normalMessage: "", errorMessage: ""}],

["consent", "Form", {consentRequired: true, html: {include: "consent.html"}}],
["intro", "Form", {consentRequired: true, html: {include: "intro.html"}}],
["debrief", "Form", {consentRequired: true, html: {include: "debrief.html"}}],

['shared-intro', "Form", {consentRequired: false, html: {include: "shared_intro1.html"}}],
['shared-intro', "Form", {consentRequired: false, html: {include: "shared_intro2.html"}}],
['shared-intro', "Form", {consentRequired: false, html: {include: "shared_intro3.html"}}],

['shared-intro', Message, {consentRequired: false,
                   html: ["div",
                           ["p", "Let's try one practice item."]
                         ]}],

['shared-intro', Separator, { transfer: 250, normalMessage: "", errorMessage: ""}, "EPDashedSentence", {s:"+"}, DS, {s:"The cute cats",as: [['s','are'],['k','is']]}],

['shared-intro', Message, {consentRequired: false,
                   html: ["div",
                           ["p", "How was that? Just try and pick whichever word seems to fit better as the next word of the sentence.  "],
                           ["p", "Many English speakers find 'are' to be a more natural completion. Let's try some more."]
                         ]}],

['shared-intro', Separator, { transfer: 250, normalMessage: "", errorMessage: ""}, "EPDashedSentence", {s:"+"}, DS, {s:"The young man behaved",as: [['s','themselves'],['k','himself']]}],
['shared-intro', Separator, { transfer: 250, normalMessage: "", errorMessage: ""}, "EPDashedSentence", {s:"+"}, DS, {s:"Mary and John",as: [['s','are'],['k','is']]}],

['shared-intro', Message, {consentRequired: false,
                   html: ["div",
                           ["p", "Alright, that's it for practice! Hit any key when you're ready to begin."]
                        ]}],

['shared-intro',"Separator",{transfer: 2500, normalMessage: "Hands in place! Your first sentence of this block will start soon."}],


//// Shared experimental items + fillers
//// ARCHITEUTHIS: Main Agreement / Reflexive comparison
[["ARCHITEUTHIS-1",1], "EPDashedSentence", {s:"+"}, DS, {s:"The father of the young boy obviously",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",1], "EPDashedSentence", {s:"+"}, DS, {s:"The father of the young boys obviously",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",1], "EPDashedSentence", {s:"+"}, DS, {s:"The father of the young boy obviously loved",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-4",1], "EPDashedSentence", {s:"+"}, DS, {s:"The father of the young boys obviously loved",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-1",2], "EPDashedSentence", {s:"+"}, DS, {s:"The father of the policeman suddenly",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",2], "EPDashedSentence", {s:"+"}, DS, {s:"The father of the policemen suddenly",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",2], "EPDashedSentence", {s:"+"}, DS, {s:"The father of the policeman suddenly doubted",as: [['s','themselves'],['k','himself']]}],
[["ARCHITEUTHIS-4",2], "EPDashedSentence", {s:"+"}, DS, {s:"The father of the policemen suddenly doubted",as: [['s','themselves'],['k','himself']]}],
[["ARCHITEUTHIS-1",3], "EPDashedSentence", {s:"+"}, DS, {s:"The grandfather of the young man always",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",3], "EPDashedSentence", {s:"+"}, DS, {s:"The grandfather of the young men always",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",3], "EPDashedSentence", {s:"+"}, DS, {s:"The grandfather of the young man always suggested",as: [['s','themselves'],['k','himself']]}],
[["ARCHITEUTHIS-4",3], "EPDashedSentence", {s:"+"}, DS, {s:"The grandfather of the young men always suggested",as: [['s','themselves'],['k','himself']]}],
[["ARCHITEUTHIS-1",4], "EPDashedSentence", {s:"+"}, DS, {s:"The stableboy of the prince always",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",4], "EPDashedSentence", {s:"+"}, DS, {s:"The stableboy of the princes always",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",4], "EPDashedSentence", {s:"+"}, DS, {s:"The stableboy of the prince always amused",as: [['s','themselves'],['k','himself']]}],
[["ARCHITEUTHIS-4",4], "EPDashedSentence", {s:"+"}, DS, {s:"The stableboy of the princes always amused",as: [['s','themselves'],['k','himself']]}],
[["ARCHITEUTHIS-1",5], "EPDashedSentence", {s:"+"}, DS, {s:"The busboy for the waiter always",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",5], "EPDashedSentence", {s:"+"}, DS, {s:"The busboy for the waiters always",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",5], "EPDashedSentence", {s:"+"}, DS, {s:"The busboy for the waiter always asserted",as: [['s','themselves'],['k','himself']]}],
[["ARCHITEUTHIS-4",5], "EPDashedSentence", {s:"+"}, DS, {s:"The busboy for the waiters always asserted",as: [['s','themselves'],['k','himself']]}],
[["ARCHITEUTHIS-1",6], "EPDashedSentence", {s:"+"}, DS, {s:"The boy with the policeman always",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",6], "EPDashedSentence", {s:"+"}, DS, {s:"The boy with the policemen always",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",6], "EPDashedSentence", {s:"+"}, DS, {s:"The boy with the policeman always amused",as: [['s','themselves'],['k','himself']]}],
[["ARCHITEUTHIS-4",6], "EPDashedSentence", {s:"+"}, DS, {s:"The boy with the policemen always amused",as: [['s','themselves'],['k','himself']]}],
[["ARCHITEUTHIS-1",7], "EPDashedSentence", {s:"+"}, DS, {s:"The brother of the choirboy finally",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",7], "EPDashedSentence", {s:"+"}, DS, {s:"The brother of the choirboys finally",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",7], "EPDashedSentence", {s:"+"}, DS, {s:"The brother of the choirboy finally asserted",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-4",7], "EPDashedSentence", {s:"+"}, DS, {s:"The brother of the choirboys finally asserted",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-1",8], "EPDashedSentence", {s:"+"}, DS, {s:"The brother of the male model definitely",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",8], "EPDashedSentence", {s:"+"}, DS, {s:"The brother of the male models definitely",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",8], "EPDashedSentence", {s:"+"}, DS, {s:"The brother of the male model definitely found",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-4",8], "EPDashedSentence", {s:"+"}, DS, {s:"The brother of the male models definitely found",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-1",9], "EPDashedSentence", {s:"+"}, DS, {s:"The poolboy of the congressman suddenly",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",9], "EPDashedSentence", {s:"+"}, DS, {s:"The poolboy of the congressmen suddenly",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",9], "EPDashedSentence", {s:"+"}, DS, {s:"The poolboy of the congressman suddenly threw",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-4",9], "EPDashedSentence", {s:"+"}, DS, {s:"The poolboy of the congressmen suddenly threw",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-1",10], "EPDashedSentence", {s:"+"}, DS, {s:"The priest with the bishop usually",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",10], "EPDashedSentence", {s:"+"}, DS, {s:"The priest with the bishops usually",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",10], "EPDashedSentence", {s:"+"}, DS, {s:"The priest with the bishop usually appointed",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-4",10], "EPDashedSentence", {s:"+"}, DS, {s:"The priest with the bishops usually appointed",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-1",11], "EPDashedSentence", {s:"+"}, DS, {s:"The doctor of the baseball player probably",as: [['s','have'],['k','has']]}], 
[["ARCHITEUTHIS-2",11], "EPDashedSentence", {s:"+"}, DS, {s:"The doctor of the baseball players probably",as: [['s','have'],['k','has']]}], 
[["ARCHITEUTHIS-3",11], "EPDashedSentence", {s:"+"}, DS, {s:"The doctor of the baseball player probably hired",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-4",11], "EPDashedSentence", {s:"+"}, DS, {s:"The doctor of the baseball players probably hired",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-1",12], "EPDashedSentence", {s:"+"}, DS, {s:"The chauffeur of the CEO certainly",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",12], "EPDashedSentence", {s:"+"}, DS, {s:"The chauffeur of the CEOs certainly",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",12], "EPDashedSentence", {s:"+"}, DS, {s:"The chauffeur of the CEO certainly embarrassed",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-4",12], "EPDashedSentence", {s:"+"}, DS, {s:"The chauffeur of the CEOs certainly embarrassed",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-1",13], "EPDashedSentence", {s:"+"}, DS, {s:"The bodyguard of the actor surprisingly",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",13], "EPDashedSentence", {s:"+"}, DS, {s:"The bodyguard of the actors surprisingly",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",13], "EPDashedSentence", {s:"+"}, DS, {s:"The bodyguard of the actor surprisingly prepared",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-4",13], "EPDashedSentence", {s:"+"}, DS, {s:"The bodyguard of the actors surprisingly prepared",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-1",14], "EPDashedSentence", {s:"+"}, DS, {s:"The uncle of the sailor always",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",14], "EPDashedSentence", {s:"+"}, DS, {s:"The uncle of the sailors always",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",14], "EPDashedSentence", {s:"+"}, DS, {s:"The uncle of the sailor always confused",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-4",14], "EPDashedSentence", {s:"+"}, DS, {s:"The uncle of the sailors always confused",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-1",15], "EPDashedSentence", {s:"+"}, DS, {s:"The prisoner of the FBI agent probably",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",15], "EPDashedSentence", {s:"+"}, DS, {s:"The prisoner of the FBI agents probably",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",15], "EPDashedSentence", {s:"+"}, DS, {s:"The prisoner of the FBI agent probably protected",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-4",15], "EPDashedSentence", {s:"+"}, DS, {s:"The prisoner of the FBI agents probably protected",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-1",16], "EPDashedSentence", {s:"+"}, DS, {s:"The blacksmith of the wealthy townsman actually",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",16], "EPDashedSentence", {s:"+"}, DS, {s:"The blacksmith of the wealthy townsmen actually",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",16], "EPDashedSentence", {s:"+"}, DS, {s:"The blacksmith of the wealthy townsman actually suggested",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-4",16], "EPDashedSentence", {s:"+"}, DS, {s:"The blacksmith of the wealthy townsmen actually suggested",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-1",17], "EPDashedSentence", {s:"+"}, DS, {s:"The murderer of the prince probably",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",17], "EPDashedSentence", {s:"+"}, DS, {s:"The murderer of the princes probably",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",17], "EPDashedSentence", {s:"+"}, DS, {s:"The murderer of the prince probably disguised",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-4",17], "EPDashedSentence", {s:"+"}, DS, {s:"The murderer of the princes probably disguised",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-1",18], "EPDashedSentence", {s:"+"}, DS, {s:"The captain of the pirate somehow",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",18], "EPDashedSentence", {s:"+"}, DS, {s:"The captain of the pirates somehow",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",18], "EPDashedSentence", {s:"+"}, DS, {s:"The captain of the pirate somehow untied",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-4",18], "EPDashedSentence", {s:"+"}, DS, {s:"The captain of the pirates somehow untied",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-1",19], "EPDashedSentence", {s:"+"}, DS, {s:"The deputy of the sheriff surprisingly",as: [['s','have'],['k','has']]}], 
[["ARCHITEUTHIS-2",19], "EPDashedSentence", {s:"+"}, DS, {s:"The deputy of the sheriffs surprisingly",as: [['s','have'],['k','has']]}], 
[["ARCHITEUTHIS-3",19], "EPDashedSentence", {s:"+"}, DS, {s:"The deputy of the sheriff surprisingly pardoned",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-4",19], "EPDashedSentence", {s:"+"}, DS, {s:"The deputy of the sheriffs surprisingly pardoned",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-1",20], "EPDashedSentence", {s:"+"}, DS, {s:"The uncle of the police officer never",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",20], "EPDashedSentence", {s:"+"}, DS, {s:"The uncle of the police officers never",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",20], "EPDashedSentence", {s:"+"}, DS, {s:"The uncle of the police officer never hated",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-4",20], "EPDashedSentence", {s:"+"}, DS, {s:"The uncle of the police officers never hated",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-1",21], "EPDashedSentence", {s:"+"}, DS, {s:"The squire of the knight usually",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",21], "EPDashedSentence", {s:"+"}, DS, {s:"The squire of the knights usually",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",21], "EPDashedSentence", {s:"+"}, DS, {s:"The squire of the knight usually trusted",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-4",21], "EPDashedSentence", {s:"+"}, DS, {s:"The squire of the knights usually trusted",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-1",22], "EPDashedSentence", {s:"+"}, DS, {s:"The coach of the hockey player actually",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",22], "EPDashedSentence", {s:"+"}, DS, {s:"The coach of the hockey players actually",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",22], "EPDashedSentence", {s:"+"}, DS, {s:"The coach of the hockey player actually surprised",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-4",22], "EPDashedSentence", {s:"+"}, DS, {s:"The coach of the hockey players actually surprised",as: [['s','themselves'],['k','himself']]}],
[["ARCHITEUTHIS-1",23], "EPDashedSentence", {s:"+"}, DS, {s:"The killer of the helpless man somehow",as: [['s','have'],['k','has']]}], 
[["ARCHITEUTHIS-2",23], "EPDashedSentence", {s:"+"}, DS, {s:"The killer of the helpless men somehow",as: [['s','have'],['k','has']]}], 
[["ARCHITEUTHIS-3",23], "EPDashedSentence", {s:"+"}, DS, {s:"The killer of the helpless man somehow protected",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-4",23], "EPDashedSentence", {s:"+"}, DS, {s:"The killer of the helpless men somehow protected",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-1",24], "EPDashedSentence", {s:"+"}, DS, {s:"The handsome client of the businessman sadly",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",24], "EPDashedSentence", {s:"+"}, DS, {s:"The handsome client of the businessmen sadly",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",24], "EPDashedSentence", {s:"+"}, DS, {s:"The handsome client of the businessman sadly forced",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-4",24], "EPDashedSentence", {s:"+"}, DS, {s:"The handsome client of the businessmen sadly forced",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-1",25], "EPDashedSentence", {s:"+"}, DS, {s:"The private pilot of the millionaire definitely",as: [['s','were'],['k','was']]}],
[["ARCHITEUTHIS-2",25], "EPDashedSentence", {s:"+"}, DS, {s:"The private pilot of the millionaires definitely",as: [['s','were'],['k','was']]}],
[["ARCHITEUTHIS-3",25], "EPDashedSentence", {s:"+"}, DS, {s:"The private pilot of the millionaire definitely established",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-4",25], "EPDashedSentence", {s:"+"}, DS, {s:"The private pilot of the millionaires definitely established",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-1",26], "EPDashedSentence", {s:"+"}, DS, {s:"The private detective of the governor unsurprisingly",as: [['s','have'],['k','has']]}], 
[["ARCHITEUTHIS-2",26], "EPDashedSentence", {s:"+"}, DS, {s:"The private detective of the governors unsurprisingly",as: [['s','have'],['k','has']]}], 
[["ARCHITEUTHIS-3",26], "EPDashedSentence", {s:"+"}, DS, {s:"The private detective of the governor unsurprisingly praised",as: [['s','themselves'],['k','himself']]}],
[["ARCHITEUTHIS-4",26], "EPDashedSentence", {s:"+"}, DS, {s:"The private detective of the governors unsurprisingly praised",as: [['s','themselves'],['k','himself']]}],
[["ARCHITEUTHIS-1",27], "EPDashedSentence", {s:"+"}, DS, {s:"The deliveryman for the auto mechanic somehow",as: [['s','have'],['k','has']]}], 
[["ARCHITEUTHIS-2",27], "EPDashedSentence", {s:"+"}, DS, {s:"The deliveryman for the auto mechanics somehow",as: [['s','have'],['k','has']]}], 
[["ARCHITEUTHIS-3",27], "EPDashedSentence", {s:"+"}, DS, {s:"The deliveryman for the auto mechanic somehow appointed",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-4",27], "EPDashedSentence", {s:"+"}, DS, {s:"The deliveryman for the auto mechanics somehow appointed",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-1",28], "EPDashedSentence", {s:"+"}, DS, {s:"The butler of the oil tycoon sadly",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",28], "EPDashedSentence", {s:"+"}, DS, {s:"The butler of the oil tycoons sadly",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",28], "EPDashedSentence", {s:"+"}, DS, {s:"The butler of the oil tycoon sadly terrified",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-4",28], "EPDashedSentence", {s:"+"}, DS, {s:"The butler of the oil tycoons sadly terrified",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-1",29], "EPDashedSentence", {s:"+"}, DS, {s:"The bellboy with the colonel definitely",as: [['s','were'],['k','was']]}],
[["ARCHITEUTHIS-2",29], "EPDashedSentence", {s:"+"}, DS, {s:"The bellboy with the colonels definitely",as: [['s','were'],['k','was']]}],
[["ARCHITEUTHIS-3",29], "EPDashedSentence", {s:"+"}, DS, {s:"The bellboy with the colonel definitely established",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-4",29], "EPDashedSentence", {s:"+"}, DS, {s:"The bellboy with the colonels definitely established",as: [['s','themselves'],['k','himself']]}], 
[["ARCHITEUTHIS-1",30], "EPDashedSentence", {s:"+"}, DS, {s:"The car salesman with the frat boy unsurprisingly",as: [['s','have'],['k','has']]}], 
[["ARCHITEUTHIS-2",30], "EPDashedSentence", {s:"+"}, DS, {s:"The car salesman with the frat boys unsurprisingly",as: [['s','have'],['k','has']]}], 
[["ARCHITEUTHIS-3",30], "EPDashedSentence", {s:"+"}, DS, {s:"The car salesman with the frat boy unsurprisingly suggested",as: [['s','themselves'],['k','himself']]}],
[["ARCHITEUTHIS-4",30], "EPDashedSentence", {s:"+"}, DS, {s:"The car salesman with the frat boys unsurprisingly suggested",as: [['s','themselves'],['k','himself']]}],
[["ARCHITEUTHIS-1",31], "EPDashedSentence", {s:"+"}, DS, {s:"The mother of the ballerina usually",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",31], "EPDashedSentence", {s:"+"}, DS, {s:"The mother of the ballerinas usually",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",31], "EPDashedSentence", {s:"+"}, DS, {s:"The mother of the ballerina usually invited",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-4",31], "EPDashedSentence", {s:"+"}, DS, {s:"The mother of the ballerinas usually invited",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-1",32], "EPDashedSentence", {s:"+"}, DS, {s:"The handmaiden of the princess always",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",32], "EPDashedSentence", {s:"+"}, DS, {s:"The handmaiden of the princesses always",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",32], "EPDashedSentence", {s:"+"}, DS, {s:"The handmaiden of the princess always corrected",as: [['s','themselves'],['k','herself']]}],
[["ARCHITEUTHIS-4",32], "EPDashedSentence", {s:"+"}, DS, {s:"The handmaiden of the princesses always corrected",as: [['s','themselves'],['k','herself']]}],
[["ARCHITEUTHIS-1",33], "EPDashedSentence", {s:"+"}, DS, {s:"The flowergirl with the bridesmaid always",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",33], "EPDashedSentence", {s:"+"}, DS, {s:"The flowergirl with the bridesmaids always",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",33], "EPDashedSentence", {s:"+"}, DS, {s:"The flowergirl with the bridesmaid always confused",as: [['s','themselves'],['k','herself']]}],
[["ARCHITEUTHIS-4",33], "EPDashedSentence", {s:"+"}, DS, {s:"The flowergirl with the bridesmaids always confused",as: [['s','themselves'],['k','herself']]}],
[["ARCHITEUTHIS-1",34], "EPDashedSentence", {s:"+"}, DS, {s:"The barmaid near the chatty girl always",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",34], "EPDashedSentence", {s:"+"}, DS, {s:"The barmaid near the chatty girls always",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",34], "EPDashedSentence", {s:"+"}, DS, {s:"The barmaid near the chatty girl always included",as: [['s','themselves'],['k','herself']]}],
[["ARCHITEUTHIS-4",34], "EPDashedSentence", {s:"+"}, DS, {s:"The barmaid near the chatty girls always included",as: [['s','themselves'],['k','herself']]}],
[["ARCHITEUTHIS-1",35], "EPDashedSentence", {s:"+"}, DS, {s:"The little girl near the bride always",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",35], "EPDashedSentence", {s:"+"}, DS, {s:"The little girl near the brides always",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",35], "EPDashedSentence", {s:"+"}, DS, {s:"The little girl near the bride always imitated",as: [['s','themselves'],['k','herself']]}],
[["ARCHITEUTHIS-4",35], "EPDashedSentence", {s:"+"}, DS, {s:"The little girl near the brides always imitated",as: [['s','themselves'],['k','herself']]}],
[["ARCHITEUTHIS-1",36], "EPDashedSentence", {s:"+"}, DS, {s:"The midwife for the pregnant woman usually",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",36], "EPDashedSentence", {s:"+"}, DS, {s:"The midwife for the pregnant women usually",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",36], "EPDashedSentence", {s:"+"}, DS, {s:"The midwife for the pregnant woman usually covered",as: [['s','themselves'],['k','herself']]}],
[["ARCHITEUTHIS-4",36], "EPDashedSentence", {s:"+"}, DS, {s:"The midwife for the pregnant women usually covered",as: [['s','themselves'],['k','herself']]}],
[["ARCHITEUTHIS-1",37], "EPDashedSentence", {s:"+"}, DS, {s:"The poor girl with the rich lady usually",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",37], "EPDashedSentence", {s:"+"}, DS, {s:"The poor girl with the rich ladies usually",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",37], "EPDashedSentence", {s:"+"}, DS, {s:"The poor girl with the rich lady usually embarrassed",as: [['s','themselves'],['k','herself']]}],
[["ARCHITEUTHIS-4",37], "EPDashedSentence", {s:"+"}, DS, {s:"The poor girl with the rich ladies usually embarrassed",as: [['s','themselves'],['k','herself']]}],
[["ARCHITEUTHIS-1",38], "EPDashedSentence", {s:"+"}, DS, {s:"The waitress of the businesswoman somehow",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",38], "EPDashedSentence", {s:"+"}, DS, {s:"The waitress of the businesswomen somehow",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",38], "EPDashedSentence", {s:"+"}, DS, {s:"The waitress of the businesswoman somehow calmed",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-4",38], "EPDashedSentence", {s:"+"}, DS, {s:"The waitress of the businesswomen somehow calmed",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-1",39], "EPDashedSentence", {s:"+"}, DS, {s:"The maid of the housewife finally",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",39], "EPDashedSentence", {s:"+"}, DS, {s:"The maid of the housewives finally",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",39], "EPDashedSentence", {s:"+"}, DS, {s:"The maid of the housewife finally redeemed",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-4",39], "EPDashedSentence", {s:"+"}, DS, {s:"The maid of the housewives finally redeemed",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-1",40], "EPDashedSentence", {s:"+"}, DS, {s:"The aunt of the actress definitely",as: [['s','have'],['k','has']]}], 
[["ARCHITEUTHIS-2",40], "EPDashedSentence", {s:"+"}, DS, {s:"The aunt of the actresses definitely",as: [['s','have'],['k','has']]}], 
[["ARCHITEUTHIS-3",40], "EPDashedSentence", {s:"+"}, DS, {s:"The aunt of the actress definitely established",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-4",40], "EPDashedSentence", {s:"+"}, DS, {s:"The aunt of the actresses definitely established",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-1",41], "EPDashedSentence", {s:"+"}, DS, {s:"The nurse of the elderly woman probably",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",41], "EPDashedSentence", {s:"+"}, DS, {s:"The nurse of the elderly women probably",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",41], "EPDashedSentence", {s:"+"}, DS, {s:"The nurse of the elderly woman probably appointed",as: [['s','themselves'],['k','herself']]}],
[["ARCHITEUTHIS-4",41], "EPDashedSentence", {s:"+"}, DS, {s:"The nurse of the elderly women probably appointed",as: [['s','themselves'],['k','herself']]}],
[["ARCHITEUTHIS-1",42], "EPDashedSentence", {s:"+"}, DS, {s:"The mother of the little girl thankfully",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",42], "EPDashedSentence", {s:"+"}, DS, {s:"The mother of the little girls thankfully",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",42], "EPDashedSentence", {s:"+"}, DS, {s:"The mother of the little girl thankfully restrained",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-4",42], "EPDashedSentence", {s:"+"}, DS, {s:"The mother of the little girls thankfully restrained",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-1",43], "EPDashedSentence", {s:"+"}, DS, {s:"The sister of the sorority girl probably",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",43], "EPDashedSentence", {s:"+"}, DS, {s:"The sister of the sorority girls probably",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",43], "EPDashedSentence", {s:"+"}, DS, {s:"The sister of the sorority girl probably introduced",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-4",43], "EPDashedSentence", {s:"+"}, DS, {s:"The sister of the sorority girls probably introduced",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-1",44], "EPDashedSentence", {s:"+"}, DS, {s:"The sister of the sorceress unfortunately",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",44], "EPDashedSentence", {s:"+"}, DS, {s:"The sister of the sorceresses unfortunately",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",44], "EPDashedSentence", {s:"+"}, DS, {s:"The sister of the sorceress unfortunately poisoned",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-4",44], "EPDashedSentence", {s:"+"}, DS, {s:"The sister of the sorceresses unfortunately poisoned",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-1",45], "EPDashedSentence", {s:"+"}, DS, {s:"The grandmother of the stewardess unfortunately",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",45], "EPDashedSentence", {s:"+"}, DS, {s:"The grandmother of the stewardesses unfortunately",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",45], "EPDashedSentence", {s:"+"}, DS, {s:"The grandmother of the stewardess unfortunately drove",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-4",45], "EPDashedSentence", {s:"+"}, DS, {s:"The grandmother of the stewardesses unfortunately drove",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-1",46], "EPDashedSentence", {s:"+"}, DS, {s:"The mother of the bride actually",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",46], "EPDashedSentence", {s:"+"}, DS, {s:"The mother of the brides actually",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",46], "EPDashedSentence", {s:"+"}, DS, {s:"The mother of the bride actually criticized",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-4",46], "EPDashedSentence", {s:"+"}, DS, {s:"The mother of the brides actually criticized",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-1",47], "EPDashedSentence", {s:"+"}, DS, {s:"The kindergarten teacher near the lunchlady really",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",47], "EPDashedSentence", {s:"+"}, DS, {s:"The kindergarten teacher near the lunchladies really",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",47], "EPDashedSentence", {s:"+"}, DS, {s:"The kindergarten teacher near the lunchlady really applauded",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-4",47], "EPDashedSentence", {s:"+"}, DS, {s:"The kindergarten teacher near the lunchladies really applauded",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-1",48], "EPDashedSentence", {s:"+"}, DS, {s:"The secretary of the businesswoman suddenly",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",48], "EPDashedSentence", {s:"+"}, DS, {s:"The secretary of the businesswomen suddenly",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",48], "EPDashedSentence", {s:"+"}, DS, {s:"The secretary of the businesswoman suddenly excused",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-4",48], "EPDashedSentence", {s:"+"}, DS, {s:"The secretary of the businesswomen suddenly excused",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-1",49], "EPDashedSentence", {s:"+"}, DS, {s:"The therapist of the widow eventually",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",49], "EPDashedSentence", {s:"+"}, DS, {s:"The therapist of the widows eventually",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",49], "EPDashedSentence", {s:"+"}, DS, {s:"The therapist of the widow eventually reassured",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-4",49], "EPDashedSentence", {s:"+"}, DS, {s:"The therapist of the widows eventually reassured",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-1",50], "EPDashedSentence", {s:"+"}, DS, {s:"The babysitter of the schoolgirl usually",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",50], "EPDashedSentence", {s:"+"}, DS, {s:"The babysitter of the schoolgirls usually",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",50], "EPDashedSentence", {s:"+"}, DS, {s:"The babysitter of the schoolgirl usually described",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-4",50], "EPDashedSentence", {s:"+"}, DS, {s:"The babysitter of the schoolgirls usually described",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-1",51], "EPDashedSentence", {s:"+"}, DS, {s:"The hairdresser of the supermodel actually",as: [['s','have'],['k','has']]}], 
[["ARCHITEUTHIS-2",51], "EPDashedSentence", {s:"+"}, DS, {s:"The hairdresser of the supermodels actually",as: [['s','have'],['k','has']]}], 
[["ARCHITEUTHIS-3",51], "EPDashedSentence", {s:"+"}, DS, {s:"The hairdresser of the supermodel actually praised",as: [['s','themselves'],['k','herself']]}],
[["ARCHITEUTHIS-4",51], "EPDashedSentence", {s:"+"}, DS, {s:"The hairdresser of the supermodels actually praised",as: [['s','themselves'],['k','herself']]}],
[["ARCHITEUTHIS-1",52], "EPDashedSentence", {s:"+"}, DS, {s:"The aunt of the actress definitely",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",52], "EPDashedSentence", {s:"+"}, DS, {s:"The aunt of the actresses definitely",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",52], "EPDashedSentence", {s:"+"}, DS, {s:"The aunt of the actress definitely invited",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-4",52], "EPDashedSentence", {s:"+"}, DS, {s:"The aunt of the actresses definitely invited",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-1",53], "EPDashedSentence", {s:"+"}, DS, {s:"The den mother of the girl scout probably",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",53], "EPDashedSentence", {s:"+"}, DS, {s:"The den mother of the girl scouts probably",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",53], "EPDashedSentence", {s:"+"}, DS, {s:"The den mother of the girl scout probably elected",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-4",53], "EPDashedSentence", {s:"+"}, DS, {s:"The den mother of the girl scouts probably elected",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-1",54], "EPDashedSentence", {s:"+"}, DS, {s:"The flight attendant for the businesswoman unfortunately",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",54], "EPDashedSentence", {s:"+"}, DS, {s:"The flight attendant for the businesswomen unfortunately",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",54], "EPDashedSentence", {s:"+"}, DS, {s:"The flight attendant for the businesswoman unfortunately poisoned",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-4",54], "EPDashedSentence", {s:"+"}, DS, {s:"The flight attendant for the businesswomen unfortunately poisoned",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-1",55], "EPDashedSentence", {s:"+"}, DS, {s:"The niece of the elegant lady quietly",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",55], "EPDashedSentence", {s:"+"}, DS, {s:"The niece of the elegant ladies quietly",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",55], "EPDashedSentence", {s:"+"}, DS, {s:"The niece of the elegant lady quietly amused",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-4",55], "EPDashedSentence", {s:"+"}, DS, {s:"The niece of the elegant ladies quietly amused",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-1",56], "EPDashedSentence", {s:"+"}, DS, {s:"The receptionist of the wedding planner usually",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",56], "EPDashedSentence", {s:"+"}, DS, {s:"The receptionist of the wedding planners usually",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",56], "EPDashedSentence", {s:"+"}, DS, {s:"The receptionist of the wedding planner usually included",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-4",56], "EPDashedSentence", {s:"+"}, DS, {s:"The receptionist of the wedding planners usually included",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-1",57], "EPDashedSentence", {s:"+"}, DS, {s:"The beautician of the prom queen really",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",57], "EPDashedSentence", {s:"+"}, DS, {s:"The beautician of the prom queens really",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",57], "EPDashedSentence", {s:"+"}, DS, {s:"The beautician of the prom queen really encouraged",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-4",57], "EPDashedSentence", {s:"+"}, DS, {s:"The beautician of the prom queens really encouraged",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-1",58], "EPDashedSentence", {s:"+"}, DS, {s:"The governess of the unruly girl never",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",58], "EPDashedSentence", {s:"+"}, DS, {s:"The governess of the unruly girl never",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",58], "EPDashedSentence", {s:"+"}, DS, {s:"The governess of the unruly girl never prepared",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-4",58], "EPDashedSentence", {s:"+"}, DS, {s:"The governess of the unruly girl never prepared",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-1",59], "EPDashedSentence", {s:"+"}, DS, {s:"The nanny of the well-behaved girl obviously",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",59], "EPDashedSentence", {s:"+"}, DS, {s:"The nanny of the well-behaved girls obviously",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",59], "EPDashedSentence", {s:"+"}, DS, {s:"The nanny of the well-behaved girl obviously loved",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-4",59], "EPDashedSentence", {s:"+"}, DS, {s:"The nanny of the well-behaved girls obviously loved",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-1",60], "EPDashedSentence", {s:"+"}, DS, {s:"The granddaughter of the witch usually",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-2",60], "EPDashedSentence", {s:"+"}, DS, {s:"The granddaughter of the witches usually",as: [['s','were'],['k','was']]}], 
[["ARCHITEUTHIS-3",60], "EPDashedSentence", {s:"+"}, DS, {s:"The granddaughter of the witch usually frightened",as: [['s','themselves'],['k','herself']]}], 
[["ARCHITEUTHIS-4",60], "EPDashedSentence", {s:"+"}, DS, {s:"The granddaughter of the witches usually frightened",as: [['s','themselves'],['k','herself']]}], 

//// MENTALIS
[["MENTALIS-1",61], "EPDashedSentence", {s:"+"}, DS, {s:"During the night shift, the waiter always",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",61], "EPDashedSentence", {s:"+"}, DS, {s:"During the night shift, the waiters always",as: [['s','were'],['k','was']]}],
[["MENTALIS-1",62], "EPDashedSentence", {s:"+"}, DS, {s:"At the vet's office, the dog usually",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",62], "EPDashedSentence", {s:"+"}, DS, {s:"At the vet's office, the dogs usually",as: [['s','were'],['k','was']]}],
[["MENTALIS-1",63], "EPDashedSentence", {s:"+"}, DS, {s:"After the birthday party, the girl obviously",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",63], "EPDashedSentence", {s:"+"}, DS, {s:"After the birthday party, the girls obviously",as: [['s','were'],['k','was']]}],
[["MENTALIS-1",64], "EPDashedSentence", {s:"+"}, DS, {s:"Because of the new book, the editor apparently",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",64], "EPDashedSentence", {s:"+"}, DS, {s:"Because of the new book, the editors apparently",as: [['s','were'],['k','was']]}],
[["MENTALIS-1",65], "EPDashedSentence", {s:"+"}, DS, {s:"During the lengthy trial, the lawyer supposedly",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",65], "EPDashedSentence", {s:"+"}, DS, {s:"During the lengthy trial, the lawyers supposedly",as: [['s','were'],['k','was']]}],
[["MENTALIS-1",66], "EPDashedSentence", {s:"+"}, DS, {s:"After the big fight, the boxer seemingly",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",66], "EPDashedSentence", {s:"+"}, DS, {s:"After the big fight, the boxers seemingly",as: [['s','were'],['k','was']]}],
[["MENTALIS-1",67], "EPDashedSentence", {s:"+"}, DS, {s:"For the difficult scene, the actor quietly",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",67], "EPDashedSentence", {s:"+"}, DS, {s:"For the difficult scene, the actors quietly",as: [['s','were'],['k','was']]}],
[["MENTALIS-1",68], "EPDashedSentence", {s:"+"}, DS, {s:"At the movie theater, the teenager definitely",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",68], "EPDashedSentence", {s:"+"}, DS, {s:"At the movie theater, the teenagers definitely",as: [['s','were'],['k','was']]}],
[["MENTALIS-1",69], "EPDashedSentence", {s:"+"}, DS, {s:"In the new church, the priest solemnly",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",69], "EPDashedSentence", {s:"+"}, DS, {s:"In the new church, the priests solemnly",as: [['s','were'],['k','was']]}],
[["MENTALIS-1",70], "EPDashedSentence", {s:"+"}, DS, {s:"Despite the bad review, the customer really",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",70], "EPDashedSentence", {s:"+"}, DS, {s:"Despite the bad review, the customers really",as: [['s','were'],['k','was']]}],
[["MENTALIS-1",71], "EPDashedSentence", {s:"+"}, DS, {s:"Instead of the old recipe, the chef supposedly",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",71], "EPDashedSentence", {s:"+"}, DS, {s:"Instead of the old recipe, the chefs supposedly",as: [['s','were'],['k','was']]}],
[["MENTALIS-1",72], "EPDashedSentence", {s:"+"}, DS, {s:"Throughout the boring class, the student seemingly",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",72], "EPDashedSentence", {s:"+"}, DS, {s:"Throughout the boring class, the students seemingly",as: [['s','were'],['k','was']]}],
[["MENTALIS-1",73], "EPDashedSentence", {s:"+"}, DS, {s:"Behind the old bar, the bartender usually",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",73], "EPDashedSentence", {s:"+"}, DS, {s:"Behind the old bar, the bartenders usually",as: [['s','were'],['k','was']]}],
[["MENTALIS-1",74], "EPDashedSentence", {s:"+"}, DS, {s:"In spite of the small paycheck, the worker always",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",74], "EPDashedSentence", {s:"+"}, DS, {s:"In spite of the small paycheck, the workers always",as: [['s','were'],['k','was']]}],
[["MENTALIS-1",75], "EPDashedSentence", {s:"+"}, DS, {s:"Even with the impending deadline, the professor clearly",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",75], "EPDashedSentence", {s:"+"}, DS, {s:"Even with the impending deadline, the professors clearly",as: [['s','were'],['k','was']]}],
[["MENTALIS-1",76], "EPDashedSentence", {s:"+"}, DS, {s:"Even after a difficult journey, the cowboy always",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",76], "EPDashedSentence", {s:"+"}, DS, {s:"Even after a difficult journey, the cowboys always",as: [['s','were'],['k','was']]}],
[["MENTALIS-1",77], "EPDashedSentence", {s:"+"}, DS, {s:"Despite the rainy weather, the runner probably",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",77], "EPDashedSentence", {s:"+"}, DS, {s:"Despite the rainy weather, the runners probably",as: [['s','were'],['k','was']]}],
[["MENTALIS-1",78], "EPDashedSentence", {s:"+"}, DS, {s:"Regardless of the final outcome, the doctor definitely",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",78], "EPDashedSentence", {s:"+"}, DS, {s:"Regardless of the final outcome, the doctors definitely",as: [['s','were'],['k','was']]}],
[["MENTALIS-1",79], "EPDashedSentence", {s:"+"}, DS, {s:"Aside from the leaky roof, the apartment really",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",79], "EPDashedSentence", {s:"+"}, DS, {s:"Aside from the leaky roof, the apartments really",as: [['s','were'],['k','was']]}],
[["MENTALIS-1",80], "EPDashedSentence", {s:"+"}, DS, {s:"At the old hotel, the receptionist constantly",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",80], "EPDashedSentence", {s:"+"}, DS, {s:"At the old hotel, the receptionists constantly",as: [['s','were'],['k','was']]}],
[["MENTALIS-1",81], "EPDashedSentence", {s:"+"}, DS, {s:"During the forest fire, the ranger always",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",81], "EPDashedSentence", {s:"+"}, DS, {s:"During the forest fire, the rangers always",as: [['s','were'],['k','was']]}],
[["MENTALIS-1",82], "EPDashedSentence", {s:"+"}, DS, {s:"Because of the long wait, the toddler apparently",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",82], "EPDashedSentence", {s:"+"}, DS, {s:"Because of the long wait, the toddlers apparently",as: [['s','were'],['k','was']]}],
[["MENTALIS-1",83], "EPDashedSentence", {s:"+"}, DS, {s:"After the hockey game, the referee supposedly",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",83], "EPDashedSentence", {s:"+"}, DS, {s:"After the hockey game, the referees supposedly",as: [['s','were'],['k','was']]}],
[["MENTALIS-1",84], "EPDashedSentence", {s:"+"}, DS, {s:"Before the oil change, the mechanic quickly",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",84], "EPDashedSentence", {s:"+"}, DS, {s:"Before the oil change, the mechanics quickly",as: [['s','were'],['k','was']]}],
[["MENTALIS-1",85], "EPDashedSentence", {s:"+"}, DS, {s:"During the long drought, the farmer carefully",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",85], "EPDashedSentence", {s:"+"}, DS, {s:"During the long drought, the farmers carefully",as: [['s','were'],['k','was']]}],
[["MENTALIS-1",86], "EPDashedSentence", {s:"+"}, DS, {s:"Despite the recent break-in, the guard reportedly",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",86], "EPDashedSentence", {s:"+"}, DS, {s:"Despite the recent break-in, the guards reportedly",as: [['s','were'],['k','was']]}],
[["MENTALIS-1",87], "EPDashedSentence", {s:"+"}, DS, {s:"Due to the impending deadline, the author suddenly",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",87], "EPDashedSentence", {s:"+"}, DS, {s:"Due to the impending deadline, the authors suddenly",as: [['s','were'],['k','was']]}],
[["MENTALIS-1",88], "EPDashedSentence", {s:"+"}, DS, {s:"Throughout the art show, the painter supposedly",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",88], "EPDashedSentence", {s:"+"}, DS, {s:"Throughout the art show, the painters supposedly",as: [['s','were'],['k','was']]}],
[["MENTALIS-1",89], "EPDashedSentence", {s:"+"}, DS, {s:"For the big game, the mascot always",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",89], "EPDashedSentence", {s:"+"}, DS, {s:"For the big game, the mascots always",as: [['s','were'],['k','was']]}],
[["MENTALIS-1",90], "EPDashedSentence", {s:"+"}, DS, {s:"During the complicated surgery, the nurse usually",as: [['s','were'],['k','was']]}],
[["MENTALIS-2",90], "EPDashedSentence", {s:"+"}, DS, {s:"During the complicated surgery, the nurses usually",as: [['s','were'],['k','was']]}],

//// Fillers
["filler-91", "EPDashedSentence", {s:"+"}, DS, {s:"On the fishing trip, the fisherman accidentally hurt",as: [['s','themselves'],['k','himself']]}], 
["filler-92", "EPDashedSentence", {s:"+"}, DS, {s:"During the field trip, the young student proudly introduced",as: [['s','themselves'],['k','herself']]}],
["filler-93", "EPDashedSentence", {s:"+"}, DS, {s:"According to the judge, the defendent never proved",as: [['s','themselves'],['k','himself']]}],
["filler-94", "EPDashedSentence", {s:"+"}, DS, {s:"After seeing Mary, the teacher suddenly excused",as: [['s','themselves'],['k','herself']]}],
["filler-95", "EPDashedSentence", {s:"+"}, DS, {s:"In the large class, the professor totally embarrassed",as: [['s','themselves'],['k','himself']]}], 
["filler-96", "EPDashedSentence", {s:"+"}, DS, {s:"After meeting the coach, the basketball player suddenly doubted",as: [['s','themselves'],['k','herself']]}], 
["filler-97", "EPDashedSentence", {s:"+"}, DS, {s:"At the potluck, the little boy quietly amused",as: [['s','themselves'],['k','himself']]}],
["filler-98", "EPDashedSentence", {s:"+"}, DS, {s:"In Mary's office, the student nervously described",as: [['s','themselves'],['k','herself']]}],
["filler-99", "EPDashedSentence", {s:"+"}, DS, {s:"In the burning house, the firefighter heavily protected",as: [['s','themselves'],['k','himself']]}],
["filler-100", "EPDashedSentence", {s:"+"}, DS, {s:"On the trail, the forest ranger always enjoyed",as: [['s','themselves'],['k','herself']]}],
["filler-101", "EPDashedSentence", {s:"+"}, DS, {s:"According to the busboy, the customer totally embarrassed",as: [['s','themselves'],['k','himself']]}],
["filler-102", "EPDashedSentence", {s:"+"}, DS, {s:"Without a doubt, the kid quickly washed",as: [['s','themselves'],['k','herself']]}], 
["filler-103", "EPDashedSentence", {s:"+"}, DS, {s:"Before serving any customer, the mixologist always reminded",as: [['s','themselves'],['k','himself']]}],
["filler-104", "EPDashedSentence", {s:"+"}, DS, {s:"Outside the cabin, the woman quietly relaxed",as: [['s','themselves'],['k','herself']]}],
["filler-105", "EPDashedSentence", {s:"+"}, DS, {s:"Just after the dinner, the host promptly excused",as: [['s','themselves'],['k','himself']]}],
["filler-106", "EPDashedSentence", {s:"+"}, DS, {s:"Even without a chaperone, the students somehow hurt",as: [['s','themselves'],['k','himself']]}],
["filler-107", "EPDashedSentence", {s:"+"}, DS, {s:"Without a single friend, the lonely kids always introduced",as: [['s','themselves'],['k','herself']]}], 
["filler-108", "EPDashedSentence", {s:"+"}, DS, {s:"Next to the cat, the dogs constantly scratched",as: [['s','themselves'],['k','himself']]}], 
["filler-109", "EPDashedSentence", {s:"+"}, DS, {s:"Behind the big bouncer, the clubgoers nervously examined",as: [['s','themselves'],['k','herself']]}], 
["filler-110", "EPDashedSentence", {s:"+"}, DS, {s:"Next to the DJ, the dancers enthusiastically threw",as: [['s','themselves'],['k','himself']]}],
["filler-111", "EPDashedSentence", {s:"+"}, DS, {s:"According to the meteorologist, the commuters obviously endangered",as: [['s','themselves'],['k','herself']]}], 
["filler-112", "EPDashedSentence", {s:"+"}, DS, {s:"To frighten the child, the nasty teenagers apparently dressed",as: [['s','themselves'],['k','himself']]}], 
["filler-113", "EPDashedSentence", {s:"+"}, DS, {s:"To teach the rookie player, the coaches slowly explained",as: [['s','themselves'],['k','herself']]}], 
["filler-114", "EPDashedSentence", {s:"+"}, DS, {s:"Before seeing the principal, the students secretly organized",as: [['s','themselves'],['k','himself']]}],
["filler-115", "EPDashedSentence", {s:"+"}, DS, {s:"At the state fair, the passerby carefully examined",as: [['s','themselves'],['k','herself']]}], 
["filler-116", "EPDashedSentence", {s:"+"}, DS, {s:"To protect the patient, the doctors thoroughly washed",as: [['s','themselves'],['k','himself']]}],
["filler-117", "EPDashedSentence", {s:"+"}, DS, {s:"At the lake house, the artists hopefully inspired",as: [['s','themselves'],['k','herself']]}], 
["filler-118", "EPDashedSentence", {s:"+"}, DS, {s:"At the mall foodcourt, the teenagers lazily amused",as: [['s','themselves'],['k','himself']]}],
["filler-119", "EPDashedSentence", {s:"+"}, DS, {s:"In the final boss fight, the knights accidentally hurt",as: [['s','themselves'],['k','himself']]}],
["filler-120", "EPDashedSentence", {s:"+"}, DS, {s:"During the public lecture, the political scientists carefully explained",as: [['s','themselves'],['k','herself']]}],
["filler-121", "EPDashedSentence", {s:"+"}, DS, {s:"The cow and the cute pony obviously",as: [['s','were'],['k','was']]}],
["filler-122", "EPDashedSentence", {s:"+"}, DS, {s:"The student and the black belt clearly",as: [['s','were'],['k','was']]}],
["filler-123", "EPDashedSentence", {s:"+"}, DS, {s:"The bus driver and the rider apparently",as: [['s','were'],['k','was']]}],
["filler-124", "EPDashedSentence", {s:"+"}, DS, {s:"The young poet and his adoring fan pretty much",as: [['s','were'],['k','was']]}],
["filler-125", "EPDashedSentence", {s:"+"}, DS, {s:"The troubled youth and the teacher always",as: [['s','were'],['k','was']]}],
["filler-126", "EPDashedSentence", {s:"+"}, DS, {s:"The political operative and the undercover reporter secretly",as: [['s','were'],['k','was']]}],
["filler-127", "EPDashedSentence", {s:"+"}, DS, {s:"The fashion icon and the forgotten pop star really",as: [['s','were'],['k','was']]}],
["filler-128", "EPDashedSentence", {s:"+"}, DS, {s:"The red car that the drivers usually",as: [['s','have'],['k','has']]}],
["filler-129", "EPDashedSentence", {s:"+"}, DS, {s:"The young horse that the riders apparently",as: [['s','have'],['k','has']]}],
["filler-130", "EPDashedSentence", {s:"+"}, DS, {s:"The talented artist that the students never",as: [['s','have'],['k','has']]}],
["filler-131", "EPDashedSentence", {s:"+"}, DS, {s:"The guitar player that the fans probably",as: [['s','were'],['k','was']]}],
["filler-132", "EPDashedSentence", {s:"+"}, DS, {s:"The tough class that the middle schoolers totally",as: [['s','were'],['k','was']]}],
["filler-133", "EPDashedSentence", {s:"+"}, DS, {s:"The difficult operation that the surgeons never",as: [['s','have'],['k','has']]}],
["filler-134", "EPDashedSentence", {s:"+"}, DS, {s:"The festival that the townsfolk always",as: [['s','have'],['k','has']]}],
["filler-135", "EPDashedSentence", {s:"+"}, DS, {s:"The heinous crime that the mobsters obviously",as: [['s','are'],['k','is']]}],
["filler-136", "EPDashedSentence", {s:"+"}, DS, {s:"The coder and the graphic designer quickly corrected",as: [['s','themselves'],['k','himself']]}],
["filler-137", "EPDashedSentence", {s:"+"}, DS, {s:"The mechanic and his nervous apprentice casually introduced",as: [['s','themselves'],['k','himself']]}],
["filler-138", "EPDashedSentence", {s:"+"}, DS, {s:"The dirty child and the puppy thoroughly washed",as: [['s','themselves'],['k','herself']]}],
["filler-139", "EPDashedSentence", {s:"+"}, DS, {s:"The captain and the rowdy pirates successfully enriched",as: [['s','themselves'],['k','himself']]}],
["filler-140", "EPDashedSentence", {s:"+"}, DS, {s:"The lead singer and the new drummer totally embarrassed",as: [['s','themselves'],['k','himself']]}],
["filler-141", "EPDashedSentence", {s:"+"}, DS, {s:"The senator and her aide obviously contradicted",as: [['s','themselves'],['k','herself']]}],
["filler-142", "EPDashedSentence", {s:"+"}, DS, {s:"The careful scientist and the lab assistant corrected",as: [['s','themselves'],['k','herself']]}],
["filler-143", "EPDashedSentence", {s:"+"}, DS, {s:"The cake that the bakers lovingly baked",as: [['s','themselves'],['k','herself']]}],
["filler-144", "EPDashedSentence", {s:"+"}, DS, {s:"The party that the high school kids secretly threw",as: [['s','themselves'],['k','himself']]}],
["filler-145", "EPDashedSentence", {s:"+"}, DS, {s:"The real reason that the French students always secluded",as: [['s','themselves'],['k','himself']]}],
["filler-146", "EPDashedSentence", {s:"+"}, DS, {s:"The birthday gift that the twin girls gave",as: [['s','themselves'],['k','herself']]}],
["filler-147", "EPDashedSentence", {s:"+"}, DS, {s:"The amazing painting that the students apparently painted",as: [['s','themselves'],['k','herself']]}],
["filler-148", "EPDashedSentence", {s:"+"}, DS, {s:"The video game that the young boys proudly bought",as: [['s','themselves'],['k','himself']]}],
["filler-149", "EPDashedSentence", {s:"+"}, DS, {s:"The website that the coders evidently designed",as: [['s','themselves'],['k','himself']]}],
["filler-150", "EPDashedSentence", {s:"+"}, DS, {s:"The incredible dress that the designers carefully sewed",as: [['s','themselves'],['k','herself']]}]
];
